### ISSUE TITLE
无法正确显示/help/中的文档 + 对于文档页面的美化

### ISSUE THREAD

**Issue by 0x24a** [Hiyoteam/hackchat-client-plus#10]
在cf代理站点（https://hc.thz.cool/）无法正确显示help中的文档。

顺便，认为文档页面不够美观，可以使用pico.css

**Comment by xjzh123** [comment]
在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯在快乐健康在还真的是哈迪斯

**Comment by 0x24a** [comment]
纠正：目前在https://hach.chat/可以正常使用
https://hc.thz.cool/即将弃用
