### ISSUE TITLE
？

### ISSUE THREAD

**Issue by xjzh123** [Hiyoteam/hackchat-client-plus#12]
我移过来历史书，移过来hc++，不仅不给我组织权限，也不给我repo权限，我都不能commit，搞个什么review使我无法commit，气死我了

**Comment by therebe4** [comment]
还指望我支持hc.thz.cool，还要加谷歌分析，你要加谷歌分析，我就解绑netlify，重新上传repo，自己搞

**Comment by therebe4** [comment]
他妈气死我了

**Comment by therebe4** [comment]
凭什么不给我commit

**Comment by therebe4** [comment]
还要review，你怎么不要review

**Comment by therebe4** [comment]
啊？？

**Comment by therebe4** [comment]
我他妈

**Comment by therebe4** [comment]
凭什么要review

**Comment by therebe4** [comment]
凭什么？

**Comment by therebe4** [comment]
凭什么不把我设为代码审查人员？

**Comment by therebe4** [comment]
我写得代码多还是你写的代码多，为什么我要你review

**Comment by therebe4** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by therebe4** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by therebe4** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by 0x24a** [comment]
别激动，你看hc

**Comment by 0x24a** [comment]
我也是服了啊

**Comment by 0x24a** [comment]
你看hc啊啊啊!!!!!!!!!

**Comment by 0x24a** [comment]
你看hc啊啊啊!!!!!!!!!

**Comment by 0x24a** [comment]
你看hc啊啊啊!!!!!!!!!

**Comment by therebe4** [comment]
你怎么不搜索一下，怎么unprotect，或者先给我approval review

**Comment by therebe4** [comment]
woshi伞兵好了吧

**Comment by 0x24a** [comment]
我都不知道发生什么了，我正在弄，求你啦别急

**Comment by MaggieLOL** [comment]
![IMG_20230415_210122.jpg](https://user-images.githubusercontent.com/96947247/232225355-8406fc8a-fd27-43cf-9695-f95138f9914e.jpg)

你有权限啊

**Comment by therebe4** [comment]
aaaa我是伞兵

**Comment by therebe4** [comment]
我看看

**Comment by MaggieLOL** [comment]
![IMG_20230415_210321.jpg](https://user-images.githubusercontent.com/96947247/232225468-a10b74bd-5ce0-48f8-ac8f-0a82ec2c6591.jpg)

好了

**Comment by paperee** [comment]
我去 我挖到了什么坟

**Comment by singer01** [comment]
凭什么他发社区问题就可以，我发就不行？

**Comment by Chihaya-Yuka** [comment]
哈哈哈哈哈哈哈哈哈

**Comment by 0x24a** [comment]
> 哈哈哈哈哈哈哈哈哈

再挖坟我就挖你黑历史（阴沉.png
