### ISSUE TITLE
hook系统中出现意外的输入

### ISSUE THREAD

**Issue by cmd1152** [Hiyoteam/hackchat-client-plus#39]
在hook.register after pushmessage时，在页面开始加载时会立刻报错，debug发现是args是undefined，如果真要空的，应该是个空数组，而不是undefined（报错是无法从undefined中读取0）
建议hook.run加个判断

**Comment by therebe4** [comment]
这个问题有点奇怪……

**Comment by therebe4** [comment]
我没有发现为什么会这样

**Comment by therebe4** [comment]
我知道问题所在了
https://github.com/Hiyoteam/hackchat-client-plus/blob/e3f006638bef5552db6df99a3f69eb26e358d846/src/hooks.js#L16
args被赋值了

**Comment by therebe4** [comment]
79322f0 已修复
