### ISSUE TITLE
被移动后侧边栏不会显示最新的在线列表，尽管有onlineSet

### ISSUE THREAD

**Issue by cmd1152** [Hiyoteam/hackchat-client-plus#40]
在被MoveBot移动时，虽然会出现 onlineSet 的提示，而且内容是正确的，但是侧边栏在线用户列表却是空的，只有一句你被强制移动或者踢出了，无法获取在线列表，但是服务器是发送了一个onlineSet的，理论上应该正确显示（哪怕是在线列表正常，那个警告还在），但是在线列表直接为空，而且并没有接收服务器返回的onlineSet

**Comment by therebe4** [comment]
应该不会这样了
