### ISSUE TITLE
聊天室有bug

### ISSUE THREAD

**Issue by singer01** [Hiyoteam/hackchat-client-plus#66]
加入聊天后，显示Unexpected Channel xxx. You may be kicked or moved to this channel by force.无法发送和接收消息

**Comment by 0x24a** [comment]
因为你被踢出了

**Comment by singer01** [comment]
> 因为你被踢出了

能否修复这个bug

**Comment by 0x24a** [comment]
这不是一个 Bug

**Comment by singer01** [comment]
> 因为你被踢出了，不是bug

为什么要踢出

**Comment by 0x24a** [comment]
这不属于客户端代码的范围

**Comment by 0x24a** [comment]
再次声明：GitHub 是你遇到 Bug 的时候提出问题的地方，如果你在社区遇到问题，不要在 Issues 提问！

**Comment by cmd1152** [comment]
> 加入聊天后，显示Unexpected Channel xxx. You may be kicked or moved to this channel by force.无法发送和接收消息

请使用翻译，这个意思是告诉你当前频道异常，你可能被踢出或强制移动了
