### ISSUE TITLE
区别对待？

### ISSUE THREAD

**Issue by singer01** [Hiyoteam/hackchat-client-plus#67]
https://github.com/Hiyoteam/hackchat-client-plus/issues/12
为什么他讨论社区问题就行，我就不行？
如果封禁我，请给我一个理由

**Comment by 0x24a** [comment]
那是因为误操作，并且那是和代码有关的。
那件事是因为我误配置 Push Rule，导致他无法 Push
你这是偷换概念。

**Comment by singer01** [comment]
> 那是因为误操作，并且那是和代码有关的。 那件事是因为我误配置 Push Rule，导致他无法 Push 你这是偷换概念。

你们封禁我不是误操作？？

**Comment by 0x24a** [comment]
> > 那是因为误操作，并且那是和代码有关的。 那件事是因为我误配置 Push Rule，导致他无法 Push 你这是偷换概念。
> 
> 你们封禁我不是误操作？？

不是误操作，并且你这个问题就已经和代码无关了
我们警告了很多次，你依然不遵守社区规则，所以我们在社区封禁你。
